#version 450

////////////////////////////////////////////////////////////////////////////////////////
layout(binding = 0, set = 0, rgba32f) writeonly uniform image2D outColorRenderTarget;
////////////////////////////////////////////////////////////////////////////////////////
// Main
layout(local_size_x = 32, local_size_y = 32) in;

void main() {
    imageStore(outColorRenderTarget, ivec2(gl_GlobalInvocationID.xy), vec4(0.0f, 0.0f, 0.0f, 0.0f));
}