#version 450

//layout(binding = 0, set = 0) uniform SDFScene {
//    SDF_Node nodes[100];
//}; 

//layout (push_constant) uniform PushConstant {
//    ivec2 resolution;              
//    int sdf_node_count;       
//    int curr_draw_node_idx;
//    vec3 dir_light_pos;  
//}pc_data;
////////////////////////////////////////////////////////////////////////////////////////
// RW Resources
layout(binding = 0, set = 0, rgba16f) writeonly uniform image2D outColorRenderTarget;
//layout(binding = 1, set = 0, r32f) writeonly uniform image2D outDepthRenderTarget;

////////////////////////////////////////////////////////////////////////////////////////
// Main
layout(local_size_x = 32, local_size_y = 32) in;

void main() {
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy) / ivec2(800, 600);
    imageStore(outColorRenderTarget, ivec2(gl_GlobalInvocationID.xy), vec4(uv, 0.0f, 1.0f));
    return;
}