#version 450

//layout(binding = 0, set = 0) uniform SDFScene {
//    SDF_Node nodes[100];
//}; 

layout (push_constant) uniform PushConstant {
    mat4 view_proj;
    ivec2 resolution;    
    vec3 dir_light_pos;  
    int curr_draw_node_idx;  
}pc_data;
////////////////////////////////////////////////////////////////////////////////////////
// RW Resources
layout(binding = 0, set = 0, rgba32f) writeonly uniform image2D outColorRenderTarget;
layout(binding = 1, set = 0) uniform CSTestUBO {
    vec4 color;
}ubo;

////////////////////////////////////////////////////////////////////////////////////////
// Main
layout(local_size_x = 32, local_size_y = 32) in;

void main() {
    vec2 uv = vec2(gl_GlobalInvocationID.xy) / vec2(800, 600); // since we render the scene at a fixed resolution and also we can't resize textures rn lol
    imageStore(outColorRenderTarget, ivec2(gl_GlobalInvocationID.xy), ubo.color);
    return;
}